spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://redli.xin/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: Redli9600,.0@
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: F:/logs/sell
#  file: F:/logs/sell/sell.log
#  level:
#    com.redli.sell.LoggerTest: debug