spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://redli.xin/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: Redli9600,.0@
  jpa:
    show-sql: true
  jackson:
      default-property-inclusion: non_null
  redis:
    host: 192.168.30.113
    port: 6379
server:
    context-path: /sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: F:/logs/sell
#  file: F:/logs/sell/sell.log
#  level:
#    com.redli.sell.LoggerTest: debug
wechat:
  mpAppId: wx24c4d2fcd1cea4aa
  mpAppSecret: 96c0b728d2b0debd60774d6757dde137
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://reddemo.natapp1.cc
  wechatOpenAuthorize: http://reddemo.natapp1.cc
  sell: http://reddemo.natapp1.cc
